c = input("Введите координаты двух точек через запятую (4 числа)")
c = c.split(",")
ax = int(c[0])
ay = int(c[1])
bx = int(c[2])
by = int(c[3])
print("Расстояние = ", round((( (ax - bx)**2 + (ay - by)**2 )**0.5), 3))
